#:kivy 1.0
Root:
    map: map
    BoxLayout:
        orientation: 'vertical'
        MapView:
            id: map
            zoom: 17
            lat: -34.599722
            lon: -58.381944
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: .25
            Button:
                text: "Personas en Situacion de Calle"
                on_release: app.root.point(-34.599722, -58.381944)

